# Analytic reference distribution: squared Mahalanobis distance
# ============================================================================
#
# This example compares transformed sampler observations directly with a
# known probability law. It does not generate an IID reference sample and it
# does not use the repeated batch-level metrics from `build_teststatistic`.

using MCBench
using Distributions
using Plots
using Random
using Statistics

Random.seed!(20260831)

# All built-in single-Gaussian testcases provide this analytic reference:
#
#   T(x) = (x - μ)' Σ⁻¹ (x - μ)  ~  Chisq(d).
testcase = MCBench.normal_2d_strongly_correlated
reference = MCBench.reference_distribution(testcase, :squared_mahalanobis)

println("Observable: ", reference.info)
println("Analytic distribution: ", reference.distribution)

# In a real benchmark, `candidate_samples` would normally come from the
# sampler under investigation. Here we draw a compact reproducible example.
candidate_samples = MCBench.sample(testcase, 10_000)

# The result contains the transformed values, KS statistic, and p-value.
# No IID target samples are generated by this comparison.
result = MCBench.reference_distribution_test(
    testcase,
    candidate_samples,
    :squared_mahalanobis,
)

println("One-sample KS statistic: ", result.statistic)
println("One-sample KS p-value: ", result.pvalue)

# The upper panel overlays the empirical transformed distribution and the
# analytic chi-squared density. The lower panel compares their CDFs directly.
p = MCBench.plot_reference_distribution(result; save_plots=false)

output_dir = joinpath(@__DIR__, "analytic_reference_output")
mkpath(output_dir)
savefig(p, joinpath(output_dir, "squared_mahalanobis_vs_chisq.pdf"))

println("Saved plot to: ", joinpath(output_dir, "squared_mahalanobis_vs_chisq.pdf"))


# Define a custom observable and its analytic distribution
# ============================================================================
# `AnalyticReferenceDistribution` is not limited to built-in observables. Its
# first argument is a function that receives one sample as a coordinate vector
# and returns one scalar. Here we use
#
#   T(x) = x₁ + x₂.
coordinate_sum(x) = sum(x)

# A linear combination of a multivariate normal variable is normal again. For
# T(x) = 1'x, its mean is 1'μ and its variance is 1'Σ1.
target_mean = mean(testcase.f)
target_covariance = cov(testcase.f)
coordinate_sum_mean = sum(target_mean)
coordinate_sum_variance = sum(target_covariance)

coordinate_sum_distribution = Normal(
    coordinate_sum_mean,
    sqrt(coordinate_sum_variance),
)

coordinate_sum_reference = MCBench.AnalyticReferenceDistribution(
    coordinate_sum,
    coordinate_sum_distribution;
    info="Sum of coordinates",
)

# Analytic references are stored separately from known scalar reference values.
# This testcase retains the provided references and adds our custom observable.
custom_testcase = MCBench.Testcases(
    testcase.f,
    testcase.bounds,
    testcase.dim,
    "$(testcase.info)-Custom-Observable";
    reference_values=testcase.reference_values,
    reference_distributions=(
        squared_mahalanobis=reference,
        coordinate_sum=coordinate_sum_reference,
    ),
)

# The same candidate samples can be reused because the target did not change.
custom_result = MCBench.reference_distribution_test(
    custom_testcase,
    candidate_samples,
    :coordinate_sum,
)

println("\nCustom observable: ", coordinate_sum_reference.info)
println("Analytic distribution: ", coordinate_sum_reference.distribution)
println("One-sample KS statistic: ", custom_result.statistic)
println("One-sample KS p-value: ", custom_result.pvalue)

custom_plot = MCBench.plot_reference_distribution(
    custom_result;
    save_plots=false,
)
custom_plot_path = joinpath(output_dir, "coordinate_sum_vs_normal.pdf")
savefig(custom_plot, custom_plot_path)

println("Saved custom-observable plot to: ", custom_plot_path)
